name: main
on: [push]
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install node js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run Unit Test
        run: node dist/Test1.js

      - name: Run Integration Test
        run: node dist/integration.js
