name: workflow3
on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cat file index.js
        run: cat dist/index.js
