name: Workflow 3

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job1:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build (สร้าง dist/index.js)
        run: |
          npm install
          npm run build

      - name: Cat file index.js
        run: cat dist/index.js
